### ISSUE TITLE
Could not load 'plugins/BetterItemRestrict-0.9.6.jar' in folder 'plugins' org.bukkit.plugin.InvalidPluginException: Cannot find main class `net.kaikk.mc.itemrestrict.BetterItemRestrict'

### ISSUE THREAD

**Issue by FLAiRX** [KaiKikuchi/BetterItemRestrict#6]
Hi, I am getting the error below when trying to load this plugin. Obviously I have no idea why this is happening so so help would be a appreciated.
This is running on a Tekkit legends server using the latest version of Thermos

`[Server thread/ERROR]: Could not load 'plugins/BetterItemRestrict-0.9.6.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: Cannot find main class 'net.kaikk.mc.itemrestrict.BetterItemRestrict'
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:191) ~[PluginClassLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:145) ~[JavaPluginLoader.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334) ~[SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:256) [SimplePluginManager.class:1.7.10-1614.58]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:343) [CraftServer.class:1.7.10-1614.58]
	at net.minecraft.world.storage.SaveHandler.initBukkitData(SaveHandler.java:462) [ayq.class:?]
	at net.minecraft.world.storage.SaveHandler.func_75757_d(SaveHandler.java:138) [ayq.class:?]
	at net.minecraft.world.World.<init>(World.java:374) [ahb.class:?]
	at net.minecraft.world.WorldServer.<init>(WorldServer.java:162) [mt.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:375) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:337) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:643) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72]
Caused by: java.lang.ClassNotFoundException: net/kaikk/mc/itemrestrict/BetterItemRestrict
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_72]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_72]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:189) ~[PluginClassLoader.class:1.7.10-1614.58]
	... 12 more`

**Comment by spannerman79** [comment]
Did you read the readme? https://github.com/KaiKikuchi/BetterItemRestrict#dependency

**Comment by FLAiRX** [comment]
Of course I read it. I am also using Kias RTP and better chunk loaders to double answer your question. Yes I am using Kias commons

**Comment by FLAiRX** [comment]
Yes I read the read me however I think I have the wrong version of commons. Let me check. Okay I had a lower version of commons but I have updated it but I am still getting the same error
